import type { Type } from "./shared";
import type { Video } from "./videos";

export interface Channel {
  type: Type;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  authorBanners: AuthorBannerOrThumbnail[];
  authorThumbnails: AuthorBannerOrThumbnail[];
  subCount: number;
  totalViews: number;
  joined: number; // Unix timestamp (0 if not joined)
  autoGenerated: boolean;
  ageGated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: string[];
  tabs: string[];
  tags: string[];
  latestVideos: Video[];
  relatedChannels: Channel[];
}

interface AuthorBannerOrThumbnail {
  url: string;
  width: number;
  height: number;
}
