name: Create Release with webos TV IPK
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install webos-cli
        run: npm install -g @webos-tools/cli

      - name: Package the app
        run: |
          ares-package -n hosted_web_app

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install Ionic and Capacitor dependencies
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Generate Self-signed certificate
        run: npm run android:generate-key

      - name: Build Android APK
        run: npm run android:build

      - name: Rename APK file
        run: npm run android:get-apk

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Automated release v${{ github.run_number }}"

      - name: Upload IPK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: com.wristyquill.invidious_1.0.0_all.ipk

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: ./invidious-tv.apk
